### ISSUE TITLE
Mouse relative movement doesn't work.

### ISSUE THREAD

**Issue by josch1710** [bitwiseworks/SDL2-os2#5]
**Describe the bug**
If mouse relative movement is selected, the mouse movement event is followed by a mouse movement event, which negates the previous wanted movement.

**To Reproduce**
1. Build SDL2 test applications
2. Start testrelative.exe
3. Move the mouse
4. The cursor springs back to the middle of the window

**Expected behavior**
The cursor should wander about the window.

**Desktop (please complete the following information):**
- ArcaOS 2.0.7
- Most recent SDL2 from netlabs-rel.

**Comment by sezero** [comment]
Do you have a patch for this?

**Comment by josch1710** [comment]
No.

**Comment by sezero** [comment]
Email'ed Andrey Vasilkin for any insight. If anyone has a solution though, it'd be great.

**Comment by sezero** [comment]
https://github.com/libsdl-org/SDL/commit/b1324fbc9f23c2be21f923e34f4dda690ed578fa
